version: '3.9'

services:
  rethinkdb:
    image: rethinkdb:2.4
    ports:
      - 28015:28015
      - 8081:8080
    volumes:
      - /Users/vivienadnotair/unsync-documents/code/vivien/react-mineSweeper/infrastructure/rethinkdb/data:/data